services:
  slskd:
    restart: unless-stopped
    image: slskd/slskd:0.23.2
    user: "${UID-1000}:${GID-1000}"
    networks:
      - saltbox
    env_file: seed.env
    labels:
      traefik.enable: true
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-gargamelle-slskd-dany.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-gargamelle-slskd-dany.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-gargamelle-slskd-dany.rule: Host(`slskd-${SUBDOMAIN}.pantagruweb.club`)
      traefik.http.services.pantagruweb-gargamelle-slskd-dany.loadbalancer.server.port: 5030
    volumes:
      - /mnt/remote/vip-audio/Audiothèque/${COOLECTIONS_USERNAME}/downloads/slskd:/app/downloads
      - ./slskd.yml:/app/slskd.yml
      - /etc/localtime:/etc/localtime:ro

  lidarr:
    image: ghcr.io/hotio/lidarr:pr-plugins
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./lidarr:/config
      - /mnt/remote/vip-audio/Audiothèque:/music
      - /mnt/remote/vip-audio/Audiothèque/${COOLECTIONS_USERNAME}/downloads/slskd:/app/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-gargamelle-lidarr-dany.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-gargamelle-lidarr-dany.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-gargamelle-lidarr-dany.rule: Host(`lidarr-${SUBDOMAIN}.pantagruweb.club`)
      traefik.http.services.pantagruweb-gargamelle-lidarr-dany.loadbalancer.server.port: 8686
    networks:
      - saltbox
    env_file: seed.env

  bandcampsync-web:
    image: ghcr.io/constructions-incongrues/bandcampsync-flask:latest
    container_name: bandcampsync-web
    init: true
    volumes:
      - ./config.json:/app/config.json:ro,z
      - /mnt/remote/vip-audio/Audiothèque/${COOLECTIONS_USERNAME}/downloads/bandcamp:/downloads:z
    environment:
      - CONFIG_PATH=/app/config.json
    restart: unless-stopped
    networks:
      - saltbox
    labels:
      traefik.enable: true
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-gargamelle-bandcampsync-dany.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-gargamelle-bandcampsync-dany.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-gargamelle-bandcampsync-dany.rule: Host(`bandcampsync-${SUBDOMAIN}.pantagruweb.club`)
      traefik.http.services.pantagruweb-gargamelle-bandcampsync-dany.loadbalancer.server.port: 5000

networks:
  saltbox:
    external: true
